sudo: required
dist: trusty

language: python
cache: pip
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install .
    - pip install -r requirements-dev.txt
script: py.test
